version: "3.8"
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    command: "realize start"
    volumes:
      - ./backend:/go/src
    ports:
      - "8080:8080"

  frontend:
    image: node:14-buster-slim
    working_dir: /frontend
    command: bash -c "yarn && yarn dev"
    volumes:
      - ./frontend:/frontend
    ports:
      - "3000:3000"

  nginx:
    image: nginx:alpine
    volumes:
      - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "3080:80"
    depends_on:
      - backend
      - frontend
