FROM golang:1.16.3-buster

WORKDIR /go/src

RUN set -eux; \
  apt-get update; \
  apt-get install -y \
    zip; \
  go get github.com/oxequa/realize

ADD entrypoint.sh install.sh /

RUN bash -c "/install.sh"

ENTRYPOINT [ "/entrypoint.sh" ]
